# Generated by Django 5.2.7 on 2025-10-02 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de RUT inválido. Use: 12.345.678-9', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$')], verbose_name='RUT')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido. Use: +56912345678', regex='^\\+?56\\d{8,9}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('contacto_adicional', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contacto Adicional')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
