# Generated by Django 5.2.7 on 2025-10-02 14:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('año', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)], verbose_name='Año')),
                ('patente', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de patente inválido. Use: AB1234 o ABCD12', regex='^[A-Z]{2}\\d{4}$|^[A-Z]{4}\\d{2}$')], verbose_name='Patente')),
                ('color', models.CharField(choices=[('blanco', 'Blanco'), ('negro', 'Negro'), ('gris', 'Gris'), ('plata', 'Plata'), ('rojo', 'Rojo'), ('azul', 'Azul'), ('verde', 'Verde'), ('amarillo', 'Amarillo'), ('cafe', 'Café'), ('otro', 'Otro')], max_length=20, verbose_name='Color')),
                ('tipo_vehiculo', models.CharField(choices=[('auto', 'Automóvil'), ('camioneta', 'Camioneta'), ('suv', 'SUV'), ('pickup', 'Pickup'), ('van', 'Van'), ('camion', 'Camión'), ('moto', 'Motocicleta'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Vehículo')),
                ('combustible', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('gas', 'Gas'), ('electrico', 'Eléctrico'), ('hibrido', 'Híbrido')], max_length=20, verbose_name='Combustible')),
                ('kilometraje', models.PositiveIntegerField(help_text='Kilometraje actual del vehículo', verbose_name='Kilometraje')),
                ('numero_motor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Motor')),
                ('numero_chasis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Chasis')),
                ('cilindrada', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cilindrada')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['marca', 'modelo', 'año'],
            },
        ),
    ]
