# Generated by Django 5.2.7 on 2025-10-02 14:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_orden', models.CharField(max_length=10, unique=True, verbose_name='Número de Orden')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_prometida', models.DateField(verbose_name='Fecha Prometida de Entrega')),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Real de Entrega')),
                ('estado', models.CharField(choices=[('ingresado', 'Ingresado'), ('en_proceso', 'En Proceso'), ('esperando_repuestos', 'Esperando Repuestos'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='ingresado', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridad')),
                ('descripcion_trabajo', models.TextField(verbose_name='Descripción del Trabajo Solicitado')),
                ('observaciones_cliente', models.TextField(blank=True, null=True, verbose_name='Observaciones del Cliente')),
                ('observaciones_tecnico', models.TextField(blank=True, null=True, verbose_name='Observaciones del Técnico')),
                ('trabajos_realizados', models.TextField(blank=True, null=True, verbose_name='Trabajos Realizados')),
                ('precio_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Mano de Obra')),
                ('precio_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Repuestos')),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Total')),
                ('imagen_danos', models.TextField(blank=True, null=True, verbose_name='Imagen con Daños Marcados')),
                ('firma_cliente', models.TextField(blank=True, null=True, verbose_name='Firma del Cliente')),
                ('firma_tecnico', models.TextField(blank=True, null=True, verbose_name='Firma del Técnico')),
                ('recepcionista', models.CharField(max_length=100, verbose_name='Recepcionista')),
                ('tecnico_asignado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Técnico Asignado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='clientes.cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
